### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by moontaers** [JuzouSatoru2/JuzouSatoru2#3]
Hello! I hope you're doing well. I recently had the opportunity to explore your repository{CleanArchitecture}, and I must say, it's truly impressive! The content and work showcased in your repository are amazing. I was wondering if you would consider creating a YouTube video to provide a more detailed explanation of the concepts and techniques you've employed. I believe it would greatly benefit others who are interested in the subject matter. Thank you for sharing your valuable work, and I look forward to seeing more from you!

**Comment by alex289** [comment]
Hey, thanks a lot for your compliments. Im not a good speaker and have no clue about making youtube videos so I have to pass on this 😅.

I could make a Wiki in the repo which explains the patterns more detailed.

What are you exactly interested in?

**Comment by moontaers** [comment]
I appreciate your suggestion to create a comprehensive wiki that covers each layer of an application stack. It would indeed be a valuable resource for developers. However, creating a detailed wiki from scratch covering all layers would be a significant undertaking.

**Comment by alex289** [comment]
That is true. Currently I don't have the capacities to create a complete wiki including all informations but I will look into it when I have time. Thanks for your idea
